{%set name = "msg-extractor" %}
{%set version = "0.22" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/mattgwwalker/{{ name }}.git
  git_rev: v{{ version }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - imapclient
    - olefile

test:
  imports:
    - ExtractMsg

about:
  home: https://github.com/mattgwwalker/msg-extractor
  license: GPL 3.0
  license_file: LICENSE.txt
  license_family: GPL3
  summary: "Extracts emails and attachments saved in Microsoft Outlook's .msg files"
  dev_url: https://github.com/mattgwwalker/msg-extractor

extra:
  recipe-maintainers:
    - pmlandwehr
