{% set name = "msg-extractor" %}
{% set version = "0.22" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/mattgwwalker/{{ name }}/archive/v{{ version }}.tar.gz"
  sha256: "8842fd250c0ee0534ce7de86aa3d883685189191ea5fcd9886ae8a9e10b5611c"

build:
  #noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - imapclient
    - olefile
    - pip
    - python
    - tzlocal
  run:
    - imapclient
    - olefile
    - python
    - tzlocal

test:
  imports:
    - extract_msg

about:
  home: "https://github.com/mattgwwalker/msg-extractor"
  license: "GPL"
  license_family: "GPL"
  license_file: ""
  summary: "Extracts emails and attachments saved in Microsoft Outlook's .msg files"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - agcopenhaver
    - pmlandwehr
