travis:
  secure:
    BINSTAR_TOKEN: VLnZ788VSqDC41mQpIxNAEIv/6CYv+hkpnGR77ncjBqN1F0OKvePztAPLpEfldOrpv25EC7WNLfBLCxft8A7qST/gOUAklQEi6T8MxA2/8QkVwUWlIHXCrqdsoFLlHXK1s7LRik8S6ezv8F+FrKqtH9dhb/hSZgHZM40CC7htBnzdeOoW/rifYbdIvaSnQdVh43pzmaX1uQ+u3tPqX0cOiHBzow+H3fcyyhziz0G6HMthQx8WPWi435YA5zM3LsMEq5lhihnLlJIuf/Bc1s1LriygktTtcOTFebm5LuqRAXt4oFEYsvXgbWT2Nu9aMiNcDS4Rht6ORv+SeFQEI9Jg4rU4JNO9glvW+s+NesqMpERSHW2IROG1/CjTkPvDUN22e3oE4E0kNB/pM4Ph3WZ+difIyK2qs8X3Wsuc7Ed35yoNq8qPOhUhAH1hXdLn6usbSqnmKhyQYutWhXnuhPWrF1HNkNhjSc0yuPrDNuNy+fFipLT6pUxkCBGAdgK62Kw81c+I+//54oIAJ5qkwhxml3QIN7shtYVxtv+p97JPVh+/dfi7Ia1sQ0mUMQ+Na4MGSFxjJvE6DcKV6k1y9dPWGwXsMl3looLLOAApDf0yAwtvm2DeAvwdeZvRRj8HGefPoMYv5Tv4mm/z3z9Iqv78NFOF8QRiZp7AwZ8d4rXy1c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
